/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pkg3dmarkers;
import java.awt.event.KeyEvent;
import java.sql.CallableStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import java.sql.Statement;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;


/**
 *
 * @author samue
 */
public class CatalogoCuentaP extends javax.swing.JFrame {

    /**
     * Creates new form CatalogoCuentaP
     */
    
    
    public CatalogoCuentaP() {
        initComponents();
        
        mostrarCatalogo(tableCatalogo);
        centrarVentanaEnPantalla();

    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BtnInicioCatalogo = new javax.swing.JButton();
        BtnTransaCatalogo = new javax.swing.JButton();
        BtnInventarioCatalogo = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableCatalogo = new javax.swing.JTable();
        btnNuevaCuenta = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lblData = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtCuentaCodigo = new javax.swing.JTextField();
        txtCuentaNombre = new javax.swing.JTextField();
        btnGuardarCuenta = new javax.swing.JButton();
        btnCancelarNuevaCuenta = new javax.swing.JButton();
        btnModificarCuenta = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txtCod = new javax.swing.JTextField();
        btnEliminarCuenta = new javax.swing.JButton();
        txtNom = new javax.swing.JTextField();
        btnCerrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BtnInicioCatalogo.setText("Inicio");
        BtnInicioCatalogo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnInicioCatalogoActionPerformed(evt);
            }
        });
        getContentPane().add(BtnInicioCatalogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 15, 104, -1));

        BtnTransaCatalogo.setText("Transacciones");
        BtnTransaCatalogo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnTransaCatalogoActionPerformed(evt);
            }
        });
        getContentPane().add(BtnTransaCatalogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 15, -1, -1));

        BtnInventarioCatalogo.setText("Inventario");
        BtnInventarioCatalogo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnInventarioCatalogoActionPerformed(evt);
            }
        });
        getContentPane().add(BtnInventarioCatalogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 15, 104, -1));

        jLabel1.setText("Catálogo actual");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 75, -1, -1));

        tableCatalogo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tableCatalogo.setFocusable(false);
        tableCatalogo = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int colIndex){
                return false;
            }
        };
        tableCatalogo.getTableHeader().setResizingAllowed(false);
        tableCatalogo.getTableHeader().setReorderingAllowed(false);
        tableCatalogo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableCatalogoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableCatalogo);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 98, 506, 273));

        btnNuevaCuenta.setBackground(new java.awt.Color(0, 102, 0));
        btnNuevaCuenta.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnNuevaCuenta.setForeground(new java.awt.Color(255, 255, 255));
        btnNuevaCuenta.setText("Nueva Cuenta");
        btnNuevaCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevaCuentaActionPerformed(evt);
            }
        });
        getContentPane().add(btnNuevaCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 371, 121, -1));

        jLabel5.setText("Para editar un registro, haga doble clic en la fila que desea actualizar.");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 411, -1, -1));

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel3.setText("Código:");

        jLabel4.setText("Nombre:");

        txtCuentaCodigo.setEnabled(false);
        txtCuentaCodigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCuentaCodigoKeyTyped(evt);
            }
        });

        txtCuentaNombre.setEnabled(false);
        txtCuentaNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCuentaNombreKeyTyped(evt);
            }
        });

        btnGuardarCuenta.setBackground(new java.awt.Color(0, 102, 0));
        btnGuardarCuenta.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnGuardarCuenta.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardarCuenta.setText("Guardar");
        btnGuardarCuenta.setEnabled(false);
        btnGuardarCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarCuentaActionPerformed(evt);
            }
        });

        btnCancelarNuevaCuenta.setBackground(new java.awt.Color(170, 0, 0));
        btnCancelarNuevaCuenta.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnCancelarNuevaCuenta.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelarNuevaCuenta.setText("Cancelar");
        btnCancelarNuevaCuenta.setEnabled(false);
        btnCancelarNuevaCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarNuevaCuentaActionPerformed(evt);
            }
        });

        btnModificarCuenta.setBackground(new java.awt.Color(0, 89, 255));
        btnModificarCuenta.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnModificarCuenta.setForeground(new java.awt.Color(255, 255, 255));
        btnModificarCuenta.setText("Actualizar");
        btnModificarCuenta.setEnabled(false);
        btnModificarCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarCuentaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblData, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(23, 23, 23)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnModificarCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtCuentaNombre)
                                .addComponent(txtCuentaCodigo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(btnGuardarCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(btnCancelarNuevaCuenta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGap(1, 1, 1))))))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblData, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtCuentaCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtCuentaNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelarNuevaCuenta)
                    .addComponent(btnGuardarCuenta))
                .addGap(18, 18, 18)
                .addComponent(btnModificarCuenta)
                .addContainerGap(50, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 98, -1, 273));

        jLabel6.setText("Editor de registros");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 75, -1, -1));

        txtCod.setEditable(false);
        txtCod.setEnabled(false);
        getContentPane().add(txtCod, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 440, 20, -1));

        btnEliminarCuenta.setBackground(new java.awt.Color(170, 0, 0));
        btnEliminarCuenta.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnEliminarCuenta.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminarCuenta.setText("Eliminar");
        btnEliminarCuenta.setEnabled(false);
        btnEliminarCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarCuentaActionPerformed(evt);
            }
        });
        getContentPane().add(btnEliminarCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(164, 371, 121, -1));

        txtNom.setEditable(false);
        getContentPane().add(txtNom, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 440, 10, -1));

        btnCerrar.setBackground(new java.awt.Color(255, 0, 0));
        btnCerrar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnCerrar.setForeground(new java.awt.Color(255, 255, 255));
        btnCerrar.setText("Cerrar Sesión");
        btnCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCerrarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCerrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCerrarMouseExited(evt);
            }
        });
        getContentPane().add(btnCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 15, 104, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNuevaCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevaCuentaActionPerformed
        // TODO add your handling code here:
        txtCuentaCodigo.setEditable(true);
        txtCuentaNombre.setEditable(true);
        txtCuentaCodigo.setText("");
        txtCuentaNombre.setText("");
        txtCuentaCodigo.setEnabled(true);
        txtCuentaNombre.setEnabled(true);
        
        lblData.setText("Estás agregando una cuenta nueva");
        btnGuardarCuenta.setEnabled(true);        
        btnCancelarNuevaCuenta.setEnabled(true); 
        btnModificarCuenta.setEnabled(false);
        btnEliminarCuenta.setEnabled(false);
    }//GEN-LAST:event_btnNuevaCuentaActionPerformed

    //Metodo que bloquea las teclas no numericas Y limita a 5 cifras
    private void txtCuentaCodigoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCuentaCodigoKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        String text = txtCuentaCodigo.getText();

        if (!(Character.isDigit(c) || c == KeyEvent.VK_BACK_SPACE || c == KeyEvent.VK_DELETE) || (text.length() >= 5)) {
            evt.consume();
        }
    }//GEN-LAST:event_txtCuentaCodigoKeyTyped

    //Metodo que bloquea lsa teclas numericas y caracteres especiales
    private void txtCuentaNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCuentaNombreKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (!(Character.isLetter(c) || c == ' ' || c == KeyEvent.VK_BACK_SPACE || c == KeyEvent.VK_DELETE || c == '\u00E1' || c == '\u00E9' || c == '\u00ED' || c == '\u00F3' || c == '\u00FA' || c == '\u00C1' || c == '\u00C9' || c == '\u00CD' || c == '\u00D3' || c == '\u00DA' || c == '\u00F1' || c == '\u00D1')) {
            evt.consume();
        }
    }//GEN-LAST:event_txtCuentaNombreKeyTyped
       
    private void btnGuardarCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarCuentaActionPerformed
        // TODO add your handling code here:
        nuevaCuenta(txtCuentaCodigo, txtCuentaNombre);
        mostrarCatalogo(tableCatalogo);

        txtCuentaCodigo.setText("");
        txtCuentaNombre.setText("");        
    }//GEN-LAST:event_btnGuardarCuentaActionPerformed

    private void btnCancelarNuevaCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarNuevaCuentaActionPerformed
        // TODO add your handling code here:
        txtCuentaCodigo.setText("");
        txtCuentaNombre.setText("");
        txtCuentaCodigo.setEnabled(false);
        txtCuentaNombre.setEnabled(false);

        btnGuardarCuenta.setEnabled(false);
        btnModificarCuenta.setEnabled(false);
        btnCancelarNuevaCuenta.setEnabled(false);
        btnEliminarCuenta.setEnabled(false);

        lblData.setText("");
    }//GEN-LAST:event_btnCancelarNuevaCuentaActionPerformed

    private void tableCatalogoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableCatalogoMouseClicked
        // TODO add your handling code here:
        int clics = evt.getClickCount();
        int row = tableCatalogo.rowAtPoint(evt.getPoint());
        
        
        //En este caso esta eliminando un registro
        if (clics == 2) {
            //activando entradas
            seleccionarRegistro(tableCatalogo, txtCod, txtCuentaCodigo, txtCuentaNombre);
            txtCuentaCodigo.setEnabled(true);
            txtCuentaNombre.setEnabled(true);
            txtCuentaCodigo.setEditable(true);
            txtCuentaNombre.setEditable(true);

            //activando botones necesarios
            btnGuardarCuenta.setEnabled(false);
            btnModificarCuenta.setEnabled(true);
            btnCancelarNuevaCuenta.setEnabled(true);
            btnEliminarCuenta.setEnabled(false);
            lblData.setText("Estás editando la siguiente cuenta");
        } //En este caso esta editando un registro
        else {
            //Desactivando entradas
            seleccionarRegistro(tableCatalogo, txtCod, txtCod, txtNom);
            txtCuentaCodigo.setEditable(false);
            txtCuentaNombre.setEditable(false);

            //activando botones necesarios
            btnGuardarCuenta.setEnabled(false);
            btnModificarCuenta.setEnabled(false);
            btnCancelarNuevaCuenta.setEnabled(false);
            btnEliminarCuenta.setEnabled(true);
            //lblData.setText("Estás eliminando la siguiente cuenta");
            lblData.setText("");
        }
    }//GEN-LAST:event_tableCatalogoMouseClicked

    private void btnModificarCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarCuentaActionPerformed
        // TODO add your handling code here:
        editarCuenta(txtCod, txtCuentaCodigo, txtCuentaNombre);
        mostrarCatalogo(tableCatalogo);
    }//GEN-LAST:event_btnModificarCuentaActionPerformed

    private void btnEliminarCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarCuentaActionPerformed
        // TODO add your handling code here:
        eliminarCuenta(txtCod, txtNom);
        mostrarCatalogo(tableCatalogo);
    }//GEN-LAST:event_btnEliminarCuentaActionPerformed

    private void BtnInicioCatalogoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnInicioCatalogoActionPerformed
        // TODO add your handling code here:
        Inicio inicio = new Inicio();
        inicio.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BtnInicioCatalogoActionPerformed

    private void BtnTransaCatalogoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnTransaCatalogoActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
        Transacciones transaccion = new Transacciones();
        transaccion.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BtnTransaCatalogoActionPerformed

    private void BtnInventarioCatalogoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnInventarioCatalogoActionPerformed
        // TODO add your handling code here:
        InventarioCRUD inventario = new InventarioCRUD();
        inventario.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BtnInventarioCatalogoActionPerformed

    private void btnCerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCerrarMouseClicked
        // Crea una nueva instancia de NuevoVentana
        Login login = new Login();
        login.setVisible(true);
        // Cierra la ventana actual
        this.dispose();
    }//GEN-LAST:event_btnCerrarMouseClicked

    private void btnCerrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCerrarMouseEntered
        btnCerrar.setBackground(new Color(255,102,102));
        btnCerrar.setForeground(new Color(0,0,0));
    }//GEN-LAST:event_btnCerrarMouseEntered

    private void btnCerrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCerrarMouseExited
        // Regresa al color original fuera
        btnCerrar.setBackground(new Color(255, 0, 0));
        btnCerrar.setForeground(new java.awt.Color(255,255,255));
    }//GEN-LAST:event_btnCerrarMouseExited


    public void mostrarCatalogo(JTable tablaCatalogo) {
        txtCod.setVisible(false);
        txtNom.setVisible(false);
        DefaultTableModel modelo = new DefaultTableModel();

        //modelo.addColumn("id");
        modelo.addColumn("Código");
        modelo.addColumn("Nombre");

        tablaCatalogo.setModel(modelo);

        //String sql = "SELECT idcatalgo, codigo, nombrecuenta FROM catalogocuenta ORDER BY codigo::text;";
        String sql = "SELECT codigo, nombrecuenta FROM catalogocuenta ORDER BY codigo::text;";

        
        //String[] datos = new String[3];
        String[] datos = new String[2];

        Statement statement = null;

        Conexion objetoConexion = new Conexion();

        try {
            statement = objetoConexion.conectar().createStatement();


            ResultSet resultSet = statement.executeQuery(sql);

            while (resultSet.next()) {
                datos[0] = resultSet.getString(1);
                datos[1] = resultSet.getString(2);
                //datos[2] = resultSet.getString(3);
                modelo.addRow(datos);
            }

            // Codigo usado para ocultar la columna "id"
            /*
            int columnIndexToHide = 0;
            tablaCatalogo.getColumnModel().getColumn(columnIndexToHide).setMinWidth(0);
            tablaCatalogo.getColumnModel().getColumn(columnIndexToHide).setMaxWidth(0);
            tablaCatalogo.getColumnModel().getColumn(columnIndexToHide).setWidth(0);*/

            tablaCatalogo.setModel(modelo);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error: " + e.toString());

        }
    }
    
    
    public void nuevaCuenta(JTextField paramCodigo, JTextField paramNombre) {
        if (paramCodigo.getText().isEmpty() || paramNombre.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null,
                    "No se puede agregar una nueva cuenta si los campos están vacíos",
                    "Error: Campos vacíos",
                    JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        int codigo = Integer.parseInt(paramCodigo.getText());
        String nombre = paramNombre.getText();
        
        Conexion objetoConexion = new Conexion();
        
        String consulta = "insert into catalogocuenta (codigo, nombrecuenta) values (?, ?);";
        
        try {
            CallableStatement cs = objetoConexion.conectar().prepareCall(consulta);
            cs.setInt(1, codigo);
            cs.setString(2, nombre);
            
            cs.execute();
            JOptionPane.showMessageDialog(null, "Cuenta agregada");
        } catch (Exception e) {
            if (e.getMessage().contains("llave duplicada viola restricción de unicidad")) {
                JOptionPane.showMessageDialog(null,
                        "No se puede agregar una nueva cuenta con un código que ya se encuentra en uso.\n"
                        + "Sin embargo, puede modificar la cuenta existente asociada a este código.",
                        "Error: Código Duplicado",
                        JOptionPane.ERROR_MESSAGE);
            }
            else {
                JOptionPane.showMessageDialog(null, "Error: " + e.toString());
            }
        }
    }
    
    
    public void seleccionarRegistro(JTable paramTabla, JTextField paramCod,JTextField paramCodigo, JTextField paramNombre) {
        try {
            int fila = paramTabla.getSelectedRow();
            
            if(fila >= 0){
                
                paramCod.setText(paramTabla.getValueAt(fila, 0).toString());
                paramCodigo.setText(paramTabla.getValueAt(fila, 0).toString());
                paramNombre.setText(paramTabla.getValueAt(fila, 1).toString());
            }
            else {
                JOptionPane.showMessageDialog(null, "Ninguna fila ha sido seleccionada aun");
            }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error: " + e.toString());
        }   
    }
    
    
    public void editarCuenta(JTextField paramCod, JTextField paramCodigo, JTextField paramNombre) {
        if (paramCodigo.getText().isEmpty() || paramNombre.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null,
                    "No se puede actualizar una nueva cuenta si los campos están vacíos",
                    "Error: Campos vacíos",
                    JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        int codigo = Integer.parseInt(paramCodigo.getText());
        int cod = Integer.parseInt(paramCod.getText());
        String nombre = paramNombre.getText();
        
        Conexion objetoConexion = new Conexion();
        
        String consulta = "UPDATE catalogocuenta SET codigo = ?, nombrecuenta = ? WHERE catalogocuenta.codigo = ?;";
        
        int respuesta = JOptionPane.showConfirmDialog(null, "¿Estás seguro de actualizar este registro?", "Actualizar registro", JOptionPane.YES_NO_OPTION);
        
        if (respuesta == JOptionPane.YES_OPTION) {
            try {
                CallableStatement cs = objetoConexion.conectar().prepareCall(consulta);
                cs.setInt(1, codigo);
                cs.setString(2, nombre);
                cs.setInt(3, cod);
                
                cs.execute();
                JOptionPane.showMessageDialog(null, "Cuenta actualizada");
                
                // Limpia del formulario el registro editado  para evitar problemas
                txtCuentaCodigo.setText("");
                txtCuentaNombre.setText("");
                
            } catch (Exception e) {
                if (e.getMessage().contains("llave duplicada viola restricción de unicidad")) {
                    JOptionPane.showMessageDialog(null,
                            "No puedes editar la cuenta actual porque el código que intentas usar ya está en uso por otro registro.\n"
                            + "Por favor, utiliza un código único para esta cuenta.",
                            "Error: Código Duplicado",
                            JOptionPane.ERROR_MESSAGE);
                } else {
                    JOptionPane.showMessageDialog(null, "Error: " + e.toString());
                }
            }
        }
    }
    
    
    public void eliminarCuenta(JTextField paramCodigo, JTextField paramNombre) {
        int codigo = Integer.parseInt(paramCodigo.getText());
        String nombre = paramNombre.getText();

        Conexion objetoConexion = new Conexion();

        String consulta = "DELETE FROM catalogocuenta WHERE catalogocuenta.codigo = ?;";

        int respuesta = JOptionPane.showConfirmDialog(null, "¿Estás seguro de que deseas eliminar este registro?", "Eliminar registro", JOptionPane.YES_NO_OPTION);

        if (respuesta == JOptionPane.YES_OPTION) {
            try {
                int codigoAEliminar = codigo;
                String nombreAEliminar = nombre;

                CallableStatement cs = objetoConexion.conectar().prepareCall(consulta);
                cs.setInt(1, codigo);

                cs.execute();

                // Mostrando el registro eliminado
                //String mensaje = "La cuenta \n" + codigoAEliminar + ": " + nombreAEliminar + "\nHa sido eliminada.";
                //JOptionPane.showMessageDialog(null, mensaje, "Cuenta eliminada", JOptionPane.INFORMATION_MESSAGE);
                String mensaje = "¡Cuenta eliminada con éxito!\n\n";
                mensaje += "Código: " + codigoAEliminar + "\n";
                mensaje += "Nombre: " + nombreAEliminar;

                JOptionPane.showMessageDialog(null,mensaje,"Cuenta eliminada", JOptionPane.INFORMATION_MESSAGE);
                        
                // Limpia del formulario el registro eliminado  para evitar problemas
                txtCuentaCodigo.setText("");
                txtCuentaNombre.setText("");
                //txtID.setText("");

            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Error: " + e.toString());
            }
        }
    }

    private void centrarVentanaEnPantalla() {
        // Obtiene el tamaño de la pantalla
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        // Obtiene el tamaño de la ventana
        Dimension windowSize = getSize();
        // Calcula la posición en la que se debe colocar la ventana para centrarla
        int x = (screenSize.width - windowSize.width) / 2;
        int y = (screenSize.height - windowSize.height) / 2;
        // Establece la ubicación de la ventana
        setLocation(x, y);
    }


    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CatalogoCuentaP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CatalogoCuentaP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CatalogoCuentaP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CatalogoCuentaP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CatalogoCuentaP().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnInicioCatalogo;
    private javax.swing.JButton BtnInventarioCatalogo;
    private javax.swing.JButton BtnTransaCatalogo;
    private javax.swing.JButton btnCancelarNuevaCuenta;
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnEliminarCuenta;
    private javax.swing.JButton btnGuardarCuenta;
    private javax.swing.JButton btnModificarCuenta;
    private javax.swing.JButton btnNuevaCuenta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblData;
    private javax.swing.JTable tableCatalogo;
    private javax.swing.JTextField txtCod;
    private javax.swing.JTextField txtCuentaCodigo;
    private javax.swing.JTextField txtCuentaNombre;
    private javax.swing.JTextField txtNom;
    // End of variables declaration//GEN-END:variables
}
