package pkg3dmarkers;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.JOptionPane;

//@author Iván Alexander Carranza Sánchez

public class Login extends javax.swing.JFrame {

    // Inicio de Pantalla
    public Login() {
        initComponents();
        centrarVentanaEnPantalla();
        textUsuario.setForeground(new java.awt.Color(187,187,187));
        textContrasena.setForeground(new java.awt.Color(187,187,187));
    }

    //CENTRADO DE VENTANA
    private void centrarVentanaEnPantalla() {
        // Obtiene el tamaño de la pantalla
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        // Obtiene el tamaño de la ventana
        Dimension windowSize = getSize();
        // Calcula la posición en la que se debe colocar la ventana para centrarla
        int x = (screenSize.width - windowSize.width) / 2;
        int y = (screenSize.height - windowSize.height) / 2;
        // Establece la ubicación de la ventana
        setLocation(x, y);
    }

    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelConstrasena = new javax.swing.JLabel();
        labelUsuario = new javax.swing.JLabel();
        Encabezada = new javax.swing.JLabel();
        textContrasena = new javax.swing.JTextField();
        textUsuario = new javax.swing.JTextField();
        buttonCancelar = new javax.swing.JButton();
        buttonIniciarSesion = new javax.swing.JButton();
        Formulario = new javax.swing.JLabel();
        LadoDerecho = new javax.swing.JLabel();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setSize(new java.awt.Dimension(510, 316));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelConstrasena.setFont(new java.awt.Font("Dubai", 0, 18)); // NOI18N
        labelConstrasena.setForeground(new java.awt.Color(0, 0, 0));
        labelConstrasena.setText("Contraseña:");
        getContentPane().add(labelConstrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, -1, -1));

        labelUsuario.setFont(new java.awt.Font("Dubai", 0, 18)); // NOI18N
        labelUsuario.setForeground(new java.awt.Color(0, 0, 0));
        labelUsuario.setText("Usuario: ");
        getContentPane().add(labelUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, -1, -1));

        Encabezada.setFont(new java.awt.Font("Dosis ExtraBold", 0, 24)); // NOI18N
        Encabezada.setForeground(new java.awt.Color(0, 0, 0));
        Encabezada.setText("Bienvenidos");
        getContentPane().add(Encabezada, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, -1, -1));

        textContrasena.setBackground(new java.awt.Color(255, 255, 255));
        textContrasena.setFont(new java.awt.Font("Dubai", 0, 18)); // NOI18N
        textContrasena.setText("Ingrese contraseña...");
        textContrasena.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                textContrasenaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                textContrasenaFocusLost(evt);
            }
        });
        textContrasena.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                textContrasenaMouseClicked(evt);
            }
        });
        textContrasena.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textContrasenaActionPerformed(evt);
            }
        });
        getContentPane().add(textContrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, 210, 30));

        textUsuario.setBackground(new java.awt.Color(255, 255, 255));
        textUsuario.setFont(new java.awt.Font("Dubai", 0, 18)); // NOI18N
        textUsuario.setText("Ingrese usuario...");
        textUsuario.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                textUsuarioFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                textUsuarioFocusLost(evt);
            }
        });
        textUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                textUsuarioMouseClicked(evt);
            }
        });
        textUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textUsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(textUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 210, 30));

        buttonCancelar.setBackground(new java.awt.Color(255, 0, 0));
        buttonCancelar.setFont(new java.awt.Font("Dubai", 1, 18)); // NOI18N
        buttonCancelar.setForeground(new java.awt.Color(255, 255, 255));
        buttonCancelar.setText("Cancelar");
        buttonCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonCancelarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                buttonCancelarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                buttonCancelarMouseExited(evt);
            }
        });
        getContentPane().add(buttonCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, 120, 40));

        buttonIniciarSesion.setBackground(new java.awt.Color(0, 0, 255));
        buttonIniciarSesion.setFont(new java.awt.Font("Dubai", 1, 18)); // NOI18N
        buttonIniciarSesion.setForeground(new java.awt.Color(255, 255, 255));
        buttonIniciarSesion.setText("Iniciar Sesión");
        buttonIniciarSesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonIniciarSesionMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                buttonIniciarSesionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                buttonIniciarSesionMouseExited(evt);
            }
        });
        buttonIniciarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonIniciarSesionActionPerformed(evt);
            }
        });
        getContentPane().add(buttonIniciarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, 210, 40));

        Formulario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/FondoBlanco.jpg"))); // NOI18N
        getContentPane().add(Formulario, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 260, 380));

        LadoDerecho.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/3DMakers.png"))); // NOI18N
        getContentPane().add(LadoDerecho, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 30, 460, 380));

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/PantallaInicioFondo.jpg"))); // NOI18N
        Fondo.setAlignmentY(0.15F);
        getContentPane().add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 730, 430));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textContrasenaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textContrasenaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textContrasenaActionPerformed

    private void textUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textUsuarioActionPerformed

    private void buttonIniciarSesionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonIniciarSesionMouseEntered
        //Cambia el color del button adentro
        buttonIniciarSesion.setBackground(new Color(94,159,243));
        buttonIniciarSesion.setForeground(new Color(0,0,0));
       // textUsuario.setForeground(new java.awt.Color(0,0,0));
    }//GEN-LAST:event_buttonIniciarSesionMouseEntered

    private void buttonIniciarSesionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonIniciarSesionMouseExited
        // Regresa al color original fuera
        buttonIniciarSesion.setBackground(new Color(0, 0, 255));
        buttonIniciarSesion.setForeground(new java.awt.Color(255,255,255));
        //textUsuario.setForeground(new java.awt.Color(187,187,187));
    }//GEN-LAST:event_buttonIniciarSesionMouseExited

    private void buttonCancelarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonCancelarMouseEntered
       //Cambia el color del button adentro
        buttonCancelar.setBackground(new Color(255,102,102));
        buttonCancelar.setForeground(new Color(0,0,0));
    }//GEN-LAST:event_buttonCancelarMouseEntered

    private void buttonCancelarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonCancelarMouseExited
        // Regresa al color original fuera
        buttonCancelar.setBackground(new Color(255, 0, 0));
        buttonCancelar.setForeground(new java.awt.Color(255,255,255));
    }//GEN-LAST:event_buttonCancelarMouseExited

    private void textUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textUsuarioMouseClicked
        // Verificacion del textbox
        String texto = textUsuario.getText().trim();
        if (texto.equals("Ingrese usuario...")) {
            textUsuario.setText("");
            textUsuario.setForeground(new java.awt.Color(0,0,0));
        } 
    }//GEN-LAST:event_textUsuarioMouseClicked

    private void textUsuarioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textUsuarioFocusLost
        // Modificación al quitar el enfoque
        String texto = textUsuario.getText().trim();
        if (texto.isEmpty() || texto.equals(".")) {
            textUsuario.setText("Ingrese usuario...");
            textUsuario.setForeground(new java.awt.Color(187,187,187));
        }
    }//GEN-LAST:event_textUsuarioFocusLost

    private void textContrasenaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textContrasenaFocusLost
        // TODO add your handling code here:
         // Modificación al quitar el enfoque
        String texto = textContrasena.getText().trim();
        if (texto.isEmpty() || texto.equals(".")) {
            textContrasena.setText("Ingrese contraseña...");
            textContrasena.setForeground(new java.awt.Color(187,187,187));
        }
    }//GEN-LAST:event_textContrasenaFocusLost

    private void textContrasenaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textContrasenaMouseClicked
        // Verificacion del textbox
        String texto = textContrasena.getText().trim();
        if (texto.equals("Ingrese contraseña...")) {
            textContrasena.setText("");
            textContrasena.setForeground(new java.awt.Color(0,0,0));
        } 
    }//GEN-LAST:event_textContrasenaMouseClicked

    private void textUsuarioFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textUsuarioFocusGained
         // Verificacion del textbox
        String texto = textUsuario.getText().trim();
        if (texto.equals("Ingrese usuario...")) {
            textUsuario.setText("");
            textUsuario.setForeground(new java.awt.Color(0,0,0));}
    }//GEN-LAST:event_textUsuarioFocusGained

    private void textContrasenaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textContrasenaFocusGained
        // Verificacion del textbox
        String texto = textContrasena.getText().trim();
        if (texto.equals("Ingrese contraseña...")) {
            textContrasena.setText("");
            textContrasena.setForeground(new java.awt.Color(0,0,0));
        } 
    }//GEN-LAST:event_textContrasenaFocusGained

    private void buttonCancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonCancelarMouseClicked
        // Cierre de sistema
        System.exit(0);
    }//GEN-LAST:event_buttonCancelarMouseClicked

    private void buttonIniciarSesionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonIniciarSesionMouseClicked
        // Acción de inicio de sesión
        String contra = textContrasena.getText().trim(); 
        String usuario = textUsuario.getText().trim();
        String user = "3DMakers";
        String password = "SIC115";
        if(contra.equals(password) && usuario.equals(user))
        {
            // Crea una nueva instancia de NuevoVentana
            Inicio inicio = new Inicio();
            inicio.setVisible(true);
             // Cierra la ventana actual
             this.dispose();
        }
        else if ((contra.isEmpty() || contra.equals("Ingrese contraseña...")) && (usuario.isEmpty() || usuario.equals("Ingrese usuario...")))
        {
            JOptionPane.showMessageDialog(this, "Ingrese el usuario y contraseña correspondiente.", "Información no ingresada.", JOptionPane.INFORMATION_MESSAGE);
        }
        else 
        {
             JOptionPane.showMessageDialog(this, "La constraseña o el usuario se han introducido de manera erronea, por favor verificar.", "Credenciales Invalidas.", JOptionPane.ERROR_MESSAGE);
             textContrasena.setText("Ingrese contraseña...");
             textContrasena.setForeground(new java.awt.Color(187,187,187));
             textUsuario.setText("Ingrese contraseña...");
             textUsuario.setForeground(new java.awt.Color(187,187,187));
        }
    }//GEN-LAST:event_buttonIniciarSesionMouseClicked

    private void buttonIniciarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonIniciarSesionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonIniciarSesionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Encabezada;
    private javax.swing.JLabel Fondo;
    private javax.swing.JLabel Formulario;
    private javax.swing.JLabel LadoDerecho;
    private javax.swing.JButton buttonCancelar;
    private javax.swing.JButton buttonIniciarSesion;
    private javax.swing.JLabel labelConstrasena;
    private javax.swing.JLabel labelUsuario;
    private javax.swing.JTextField textContrasena;
    private javax.swing.JTextField textUsuario;
    // End of variables declaration//GEN-END:variables
}
